---
apiVersion: v1
kind: Namespace
metadata:
  name: basilica-storage
  labels:
    app.kubernetes.io/name: basilica
    app.kubernetes.io/component: storage
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
