---
envoy_gateway_version: "v1.2.3"
envoy_gateway_namespace: "envoy-gateway-system"
envoy_gateway_helm_repo: "oci://docker.io/envoyproxy/gateway-helm"
envoy_gateway_release_name: "eg"

gateway_controller_replicas: 2
gateway_controller_cpu_request: "1000m"
gateway_controller_memory_request: "4Gi"
gateway_controller_cpu_limit: "4000m"
gateway_controller_memory_limit: "8Gi"

gateway_envoy_replicas: 5
gateway_envoy_cpu_request: "2000m"
gateway_envoy_memory_request: "4Gi"
gateway_envoy_cpu_limit: "8000m"
gateway_envoy_memory_limit: "16Gi"
