output "vpc_id" {
  description = "ID of the VPC"
  value       = module.networking.vpc_id
}

output "vpc_cidr" {
  description = "CIDR block of the VPC"
  value       = module.networking.vpc_cidr
}

output "nat_gateway_public_ip" {
  description = "Public IP address of the NAT Gateway (stable outbound IP)"
  value       = module.networking.nat_gateway_public_ip
}

output "k3s_api_endpoint" {
  description = "K3s API server endpoint (Network Load Balancer DNS)"
  value       = "https://${module.k3s_nlb.nlb_dns_name}:6443"
}

output "nlb_dns_name" {
  description = "DNS name of the Network Load Balancer for K3s API"
  value       = module.k3s_nlb.nlb_dns_name
}

output "alb_dns_name" {
  description = "DNS name of the Application Load Balancer for public deployments"
  value       = module.deployments_alb.alb_dns_name
}

output "deployments_endpoint" {
  description = "Public endpoint for user deployments (will be used for Cloudflare CNAME)"
  value       = "https://${module.deployments_alb.alb_dns_name}"
}

output "vpc_peering_connection_id" {
  description = "VPC peering connection ID (if created)"
  value       = module.vpc_peering.peering_connection_id
}

output "private_route_table_id" {
  description = "Private route table ID (internal reference)"
  value       = module.networking.private_route_table_id
}

output "k3s_server_ids" {
  description = "Instance IDs of K3s server nodes"
  value       = module.k3s_servers.instance_ids
}

output "k3s_server_public_ips" {
  description = "Public IP addresses of K3s server nodes"
  value       = module.k3s_servers.public_ips
}

output "k3s_server_private_ips" {
  description = "Private IP addresses of K3s server nodes"
  value       = module.k3s_servers.private_ips
}

output "primary_server_public_ip" {
  description = "Primary K3s server public IP (for initial cluster setup)"
  value       = module.k3s_servers.primary_server_public_ip
}

output "primary_server_private_ip" {
  description = "Primary K3s server private IP (for initial cluster setup)"
  value       = module.k3s_servers.primary_server_private_ip
}

output "k3s_agent_ids" {
  description = "Instance IDs of K3s agent nodes"
  value       = module.k3s_agents.instance_ids
}

output "k3s_agent_public_ips" {
  description = "Public IP addresses of K3s agent nodes"
  value       = module.k3s_agents.public_ips
}

output "k3s_agent_private_ips" {
  description = "Private IP addresses of K3s agent nodes"
  value       = module.k3s_agents.private_ips
}

output "ansible_inventory_file" {
  description = "Path to generated Ansible inventory file"
  value       = abspath("${path.module}/../ansible/inventories/production.ini")
}

output "deployment_public_ip" {
  description = "Initial deployment public IP (primary K3s server), update to Envoy LB DNS after deployment"
  value       = var.deployment_public_ip != "" ? var.deployment_public_ip : module.k3s_servers.primary_server_public_ip
}

output "ssh_private_key_file" {
  description = "Path to SSH private key (only if generated by Terraform)"
  value       = var.ssh_key_name == "" ? abspath("${path.module}/k3s-ssh-key.pem") : "Using existing key: ${var.ssh_key_name}"
}

output "ssh_connection_commands" {
  description = "SSH connection commands for quick access"
  value = {
    primary_server = "ssh -i ${local.ssh_key_file} ubuntu@${module.k3s_servers.primary_server_public_ip}"
    all_servers = [
      for idx, ip in module.k3s_servers.public_ips :
      "ssh -i ${local.ssh_key_file} ubuntu@${ip}"
    ]
    agents = [
      for idx, ip in module.k3s_agents.public_ips :
      "ssh -i ${local.ssh_key_file} ubuntu@${ip}"
    ]
  }
}

output "cluster_info" {
  description = "K3s cluster configuration information"
  value = {
    server_count      = length(module.k3s_servers.instance_ids)
    agent_count       = length(module.k3s_agents.instance_ids)
    ha_enabled        = length(module.k3s_servers.instance_ids) > 1
    primary_server_ip = module.k3s_servers.primary_server_public_ip
    workspace         = terraform.workspace
  }
}

output "next_steps" {
  description = "Next steps to deploy K3s cluster"
  value       = <<-EOT

    K3s Infrastructure Provisioned Successfully!

    Architecture Overview:
      - 3-tier networking: Public, Private, Database subnets across 3 AZs
      - NAT Gateway: ${module.networking.nat_gateway_public_ip} (stable outbound IP)
      - Network Load Balancer: ${module.k3s_nlb.nlb_dns_name}
      - K3s API Endpoint: https://${module.k3s_nlb.nlb_dns_name}:6443

    Cluster Configuration:
      - Server nodes: ${length(module.k3s_servers.instance_ids)} (HA with embedded etcd)
      - Agent nodes: ${length(module.k3s_agents.instance_ids)}
      - All nodes in public subnets with public IPs for SSH access
      - Cross-zone load balancing enabled
      - VPC Peering: ${var.peer_vpc_id != "" ? "Enabled to ${var.peer_vpc_id}" : "Not configured"}

    Next steps:

    1. Wait for instances to initialize (~3 minutes):
       watch -n 5 'aws ec2 describe-instance-status --instance-ids ${module.k3s_servers.primary_server_id} --query "InstanceStatuses[0].InstanceStatus.Status" --output text'

    2. Access K3s cluster via NLB:
       kubectl --server https://${module.k3s_nlb.nlb_dns_name}:6443 --insecure-skip-tls-verify get nodes

    3. Or use Ansible to fetch kubeconfig:
       cd ../ansible
       ansible-playbook -i inventories/production.ini playbooks/04-maintain/kubeconfig.yml

    4. Verify cluster health:
       kubectl get nodes
       kubectl get pods --all-namespaces

    5. Deploy Basilica services:
       ansible-playbook -i inventories/production.ini playbooks/02-deploy/basilica.yml

    6. After Envoy LoadBalancer is provisioned, update deployment_public_ip:
       ENVOY_LB=$(kubectl get svc basilica-envoy -n basilica-system -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
       echo "Envoy LoadBalancer: $ENVOY_LB"

       # Update operator with correct public IP
       kubectl set env deployment/basilica-operator -n basilica-system DEPLOYMENT_PUBLIC_IP=$ENVOY_LB

       # Or re-run Terraform with the correct value
       terraform apply -var="deployment_public_ip=$ENVOY_LB" -auto-approve

    SSH Access:
    - Direct SSH access available via ./connect.sh script
    - Example: ./connect.sh k3s-server-1
    - SSH access controlled by security groups (allowed_ssh_cidr_blocks)

    Important Notes:
    - K3s cluster auto-initialized with NLB DNS in TLS SANs
    - Server discovery via shared token and NLB endpoint
    - deployment_public_ip is initially set to primary server IP: ${module.k3s_servers.primary_server_public_ip}
    - Update to Envoy LB DNS after K8s deployment (see step 6)

    Ansible Inventory: ${abspath("${path.module}/../ansible/inventories/production.ini")}

  EOT
}
