apiVersion: v1
kind: Namespace
metadata:
  name: basilica-autoscaler
  labels:
    app.kubernetes.io/name: basilica-autoscaler
    app.kubernetes.io/part-of: basilica
---
apiVersion: v1
kind: Namespace
metadata:
  name: basilica-ssh-keys
  labels:
    app.kubernetes.io/name: basilica-ssh-keys
    app.kubernetes.io/part-of: basilica
    restricted: "true"
