---
- name: Get list of mount points for {{ mounted_fs }}
  ansible.builtin.shell: |
    set -o pipefail
    awk '$2 ~ /^{{ mounted_fs | regex_escape }}/ {print $2}' /proc/mounts | sort -r || true
  args:
    executable: /bin/bash
  register: mounted_points
  changed_when: false
  tags: ['reset', 'umount']

- name: Unmount {{ mounted_fs }} and children
  ansible.builtin.mount:
    path: "{{ item }}"
    state: unmounted
  with_items: "{{ mounted_points.stdout_lines }}"
  when: mounted_points.rc == 0
  tags: ['reset', 'umount']
