---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - group_vars/all/vault.yml
    - group_vars/all/r2.yml
  tasks:
    - name: Deploy R2 credentials
      include_role:
        name: basilica-storage
