apiVersion: v1
kind: Service
metadata:
  name: affine-service
  namespace: affine-system
  labels:
    app: affine-service
    app.kubernetes.io/name: affine
    app.kubernetes.io/component: evaluation-service
spec:
  type: ClusterIP
  selector:
    app: affine-service
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
