[k3s_server]
# Single-node K3s server (AWS EC2 example)
server ansible_host=prod-k3s-server ansible_user=ubuntu ansible_become=true

[k3s_agents]
# Optional agents
agent1 ansible_host=prod-k3s-node-1 ansible_user=ubuntu ansible_become=true
#agent2 ansible_host=192.0.2.12 ansible_user=ubuntu ansible_become=true
