apiVersion: apps/v1
kind: Deployment
metadata:
  name: bob
  namespace: basilica-system
  labels:
    app: subtensor
    node: bob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subtensor
      node: bob
  template:
    metadata:
      labels:
        app: subtensor
        node: bob
    spec:
      containers:
        - name: bob
          image: ghcr.io/opentensor/subtensor-localnet:devnet-ready
          imagePullPolicy: IfNotPresent
          env:
            - name: RUST_LOG
              value: info
          args:
            - --dev
            - --bob
            - --rpc-external
            - --rpc-cors=all
            - --rpc-methods=unsafe
            - --port=30334
            - --rpc-port=9945
            - --base-path=/tmp/blockchain
            - --validator
            - --bootnodes=/dns4/alice.basilica-system.svc.cluster.local/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
            - --allow-private-ipv4
            - --discover-local
          ports:
            - name: ws
              containerPort: 9945
            - name: p2p
              containerPort: 30334
          readinessProbe:
            tcpSocket:
              port: 9945
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 9945
            initialDelaySeconds: 15
            periodSeconds: 10
      restartPolicy: Always

