apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: default-backend-policy
  namespace: basilica-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: basilica-gateway
  circuitBreaker:
    maxPendingRequests: 1024
    maxParallelRequests: 1024
  timeout:
    tcp:
      connectTimeout: 30s
    http:
      requestTimeout: 3700s
      connectionIdleTimeout: 3700s
  loadBalancer:
    type: RoundRobin
