apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: envoy-gateway-controller-pdb
  namespace: envoy-gateway-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy-gateway
      app.kubernetes.io/component: controller
  unhealthyPodEvictionPolicy: AlwaysAllow
