apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: basilica-gateway-envoy-pdb
  namespace: envoy-gateway-system
spec:
  minAvailable: 3
  selector:
    matchLabels:
      gateway.envoyproxy.io/owning-gateway-name: basilica-gateway
  unhealthyPodEvictionPolicy: IfHealthyBudget
