#!/usr/bin/env python3
"""Generate a secret-free V2 bitset ingress golden vector.

This vector is for cross-language implementations of the lean V2 ingress. It
uses a dev-only sr25519 key and a fake token secret. Do not use live keys here.

Note: sr25519 signatures are randomized. Regenerating this file can change only
`signature_b64` while preserving all canonical hashes. Tests should verify the
sample signature, not require regenerated byte equality.
"""
from __future__ import annotations

import base64
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from bittensor_wallet import Keypair

from scaffold.publisher.auth import BittensorVerifier
from scaffold.publisher import v2_bitset_submit, v2_pipeline
OUT = ROOT / "deploy" / "golden" / "v2_bitset_ingress_golden.json"


def main() -> None:
    fake_secret = "golden-v2-submit-token-secret-not-live"
    kp = Keypair.create_from_uri("//V2IngressGolden")
    submitted_at = "2026-06-30T23:30:00.000Z"
    expires_at = "2099-01-01T00:00:00.000Z"
    challenge_id = "pm-t2-e495232-s7-golden"
    epoch = 495232
    tier = 2
    seq = 7
    nvars = 10
    cnf_sha256 = hashlib.sha256(b"golden-cnf-text-v1").hexdigest()
    assignment = [1, -2, 3, -4, 5, -6, 7, -8, 9, -10]
    assignment_raw = v2_pipeline.encode_bitset_assignment(assignment)
    assignment_b64 = base64.b64encode(assignment_raw).decode("ascii")

    submit_token = v2_bitset_submit.mint_submit_token(
        secret=fake_secret,
        miner_hotkey=kp.ss58_address,
        challenge_id=challenge_id,
        epoch=epoch,
        tier=tier,
        seq=seq,
        nvars=nvars,
        cnf_sha256=cnf_sha256,
        expires_at=expires_at,
    )
    token_parts = submit_token.split(".")
    token_payload_bytes = base64.urlsafe_b64decode(
        token_parts[1] + "=" * ((4 - len(token_parts[1]) % 4) % 4)
    )
    token_sig_bytes = base64.urlsafe_b64decode(
        token_parts[2] + "=" * ((4 - len(token_parts[2]) % 4) % 4)
    )
    token_payload = json.loads(token_payload_bytes.decode("utf-8"))

    raw_submit_body = {
        "schema": v2_bitset_submit.SCHEMA,
        "card_id": "synthetic_boolean_v1",
        "miner_hotkey": kp.ss58_address,
        "submitted_at": submitted_at,
        "challenge_id": challenge_id,
        "submit_token": submit_token,
        "assignment_encoding": v2_bitset_submit.ASSIGNMENT_ENCODING,
        "assignment_b64": assignment_b64,
    }
    submit = v2_bitset_submit.normalize_submit_body(
        raw_submit_body,
        miner_hotkey=kp.ss58_address,
        submitted_at=submitted_at,
        card_id="synthetic_boolean_v1",
    )
    canonical_submit = v2_bitset_submit.canonical_submit_bytes(submit)
    signature_b64 = base64.b64encode(kp.sign(canonical_submit)).decode("ascii")
    verified = BittensorVerifier().verify(kp.ss58_address, canonical_submit, signature_b64)
    if not verified:
        raise SystemExit("generated signature did not verify")

    vector = {
        "schema": "cathedral.v2.bitset_ingress_golden.v1",
        "warning": "Dev-only vector. Fake token secret and public dev key; no live secrets.",
        "fake_submit_token_secret": fake_secret,
        "dev_key_uri": "//V2IngressGolden",
        "miner_hotkey": kp.ss58_address,
        "headers": {
            "X-Cathedral-Hotkey": kp.ss58_address,
            "X-Cathedral-Signature": signature_b64,
            "X-Cathedral-Submitted-At": submitted_at,
            "Content-Type": "application/json",
        },
        "token_payload": token_payload,
        "token_payload_canonical_json": token_payload_bytes.decode("utf-8"),
        "token_payload_sha256": hashlib.sha256(token_payload_bytes).hexdigest(),
        "token_signature_sha256": hashlib.sha256(token_sig_bytes).hexdigest(),
        "submit_token": submit_token,
        "normalized_submit_body": submit,
        "canonical_submit_json": canonical_submit.decode("utf-8"),
        "canonical_submit_sha256": hashlib.sha256(canonical_submit).hexdigest(),
        "signature_b64": signature_b64,
        "assignment": assignment,
        "assignment_raw_hex": assignment_raw.hex(),
        "assignment_b64": assignment_b64,
        "assignment_sha256": hashlib.sha256(assignment_raw).hexdigest(),
        "idempotency_key": v2_bitset_submit.idempotency_key(
            miner_hotkey=kp.ss58_address,
            challenge_id=challenge_id,
        ),
        "notes": {
            "sr25519_signature_randomized": True,
            "assignment_bit_order": "variable i stored at bit i-1, LSB-first in each byte, 1=true",
            "unused_trailing_bits": "must be zero",
        },
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(vector, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(OUT)


if __name__ == "__main__":
    main()
