[k3s_server]
# Single-node K3s server (AWS EC2 example)
# Connects like: ssh -i "~/.ssh/k3s-server.pem" ubuntu@k3s-server
server ansible_host=k3s-server ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/k3s-server.pem ansible_become=true

[k3s_agents]
# Optional agents
#agent1 ansible_host=192.0.2.11 ansible_user=ubuntu ansible_become=true
#agent2 ansible_host=192.0.2.12 ansible_user=ubuntu ansible_become=true

[k3s_cluster:children]
k3s_server
k3s_agents
